### ISSUE TITLE
Question : Usage of lpDesktop

### ISSUE THREAD

**Issue by haydenmcp** [cubiclesoft/createprocess-windows#1]
Hi There!

This looks like an awesome library. :-) Out of curiosity, I see the lpDesktop population option but after attempting to use it it doesn't seem to be interpreting the desktop name correctly. After pulling the desktop name from EnumDisplayMonitors I take that value and subsequently apply it to the lpDesktop value. However, the process doesn't launch leading me to believe an invisible environment is created for that process as the docs specify. So, my question is what value is expected by lpDesktop? What's the format of that value? Do you have an example to demonstrate this? Thank you very much for your time and help and great job on the library.

Warmest regards,
Hayden McParlane

**Comment by cubiclesoft** [comment]
As far as I know, `lpDesktop` has nothing to do with monitors and `EnumDisplayMonitors()` only appears to return the device name, not the desktop.  Desktops and Window Stations are very specific concepts within the internals of the Windows OS and are mostly used to control the security context where a process runs.  The typical format of lpDesktop is a string containing a window station and desktop name such as `"winsta0\\default"`.  You will already need to have appropriate permissions to launch a process on another desktop since this code does not make any attempt to adjust DACLs.  It's also highly probable that there's a lot of missing code that would have to be added just to get it to work:

https://support.microsoft.com/en-us/help/165194/createprocessasuser-windowstations-and-desktops

My head starts to hurt whenever I have to think about Microsoft's really awkward ACL implementation.

This project is intended to be a couple of ready-to-run executables for scripting and automation purposes.  It's not really meant to be a library or wrapper even though the source code is publicly available.

**Comment by haydenmcp** [comment]
Hahahaha, well thank you for this helpful response! This clears up a lot of confusion I was having related to the purpose of that field. :-) I really appreciate it!

**Comment by cubiclesoft** [comment]
Closing issue.
