### ISSUE TITLE
Startup info size and position parameters don't work

### ISSUE THREAD

**Issue by kosadev** [cubiclesoft/createprocess-windows#4]
Hi, I've been looking for a solution to start applications in desired size and location and I found your tool.
However, size and position parameters don't work. I'm not especially surprised as I earlier tried to do that on my own with passing STARTUPINFO structure to CreateProcessA function in C language and it also didn't work.

Does it work for you?
`./createprocess.exe /width=200 /height=800 'C:\Windows\System32\notepad.exe'`

**Comment by cubiclesoft** [comment]
From [MSDN Library](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/ns-processthreadsapi-startupinfoa):

```
For GUI processes, this is used only the first time the new process calls CreateWindow to create an overlapped window if the nWidth parameter of CreateWindow is CW_USEDEFAULT.
```

Notepad, by default, keeps track of its last position and size on the system.  Therefore, it is almost certainly NOT using CW_USEDEFAULT with CreateWindow().  As a result, it wouldn't be possible to control the window size/position from a CreateProcess() call's STARTUPINFO structure.  Many applications do the same thing as Notepad because users are picky about restoring window positioning/size between application runs.  Some aspects of STARTUPINFO are leftover from the Win 3.x and early Win95 days.

You could use SysInternals Process Monitor to watch Notepad to see where it retrieves window positioning information from (e.g. the registry).  Then you could modify that information prior to starting Notepad.  Not a particularly good general-purpose solution though.

An alternate idea would be to start the process, then hunt for a specific window in the system and then resize the window programmatically:

https://stackoverflow.com/questions/4523425/how-can-i-resize-a-specific-window-after-its-created

Again, still pretty hacky and probably error-prone.  For example, on a very busy/overloaded system, the window might not appear for 30 seconds.

**Comment by kosadev** [comment]
Thank you for the answer.

The thing with resizing application is that it first popups in other size and it can make a bad impression on user. However, I agree that there is no other option. Before I tried your tool I tried many approaches and I simply considered if you were able to handle this aspect.

I think that it's also quite hard or impossible to control the look and behavior of modern (e.g. electron based) apps with WinAPI. Unfortunately.

We can consider this issue as closed.
