### ISSUE TITLE
[Question] About Elevated -> SYSTEM

### ISSUE THREAD

**Issue by anzz1** [cubiclesoft/createprocess-windows#6]
I stumbled upon this repo only *after* searching this exact thing, not finding such a thing, and whipping up my own. Talk about reinventing the wheel, eh. 

Anyway, looking through your helpful chart on how you've implemented the process of "Elevated user -> SYSTEM user", it kinda seems overly complicated. Or am I missing something here?

As spawning a NT service and using pipe servers for communication feels kind of "messy". Why not just "borrow" the token from a existing system process, then use CreateProcessWithTokenW to spawn the new process. For the stdin/stdout/stderr redirection, you can just use standard anonymous pipes and pass their handles in StartupInfo. Also not having to load the SYSTEM user profile and registry hive is a plus, as it's much faster.

Obviously the requirement of having to spawn a new process is something that can't be got around, as it's impossible by design as a part of the security model. You can easily change the access token of an existing process by replacing it in kernel memory, but that is a 'hack' and not supported. But I think the simple implementation seen in the gist would be the next best thing which is supported.

See this gist: https://gist.github.com/anzz1/8a4896834d29c062bcadfd49ac48d882
(Apologies on bad formatting and lack of comments, it's not something I would call "release quality" code. But since you're already familiar with the subject, CTRL+F "CreateProcessWithTokenW" should get you to the meat)

**Comment by cubiclesoft** [comment]
I'm familiar with `CreateProcessWithTokenW()` and even pointed it out in the video - around 5:33 in the video, you can clearly see that I was fully aware of that function.  This tool does far more than just impersonate `NT AUTHORITY\SYSTEM`.  It can start processes for any user _without their login credentials_ and can also create child processes off the non-elevated process tree.  Anonymous pipes on Windows are also blocking, which can cause deadlocks in most scripting languages, hence the TCP/IP socket and multithreading support.  Both are useful features for this project:  https://github.com/cubiclesoft/xcron

The main reason to spawn a temporary NT service is because the elevated token for the user may not necessarily have `SE_DEBUG_PRIVILEGE`.  Without the privilege, you can't duplicate tokens of other processes.  That privilege is frequently revoked in enterprise settings by group policy but the elevated user can still create system services in such environments.  The only user in the system guaranteed to have `SE_DEBUG_PRIVILEGE` that cannot be revoked is the `NT AUTHORITY\SYSTEM` user, which, as you know, most system services run under.  So while your code might work fine in some environments such as being already elevated in a default Windows installation, it won't work in all environments.

The other reason is that the ability to call `NtCreateTokenPrivilege()` is only available to a very few select processes.  A very specific token has to be obtained by analyzing tokens across the system to locate the token of interest.  This is best done as a non-impersonated `NT AUTHORITY\SYSTEM` user, which again is system service territory.  Elevating to `NT AUTHORITY\SYSTEM` is really a byproduct/side effect of being able to create valid user tokens from scratch.

The NT Service method is mostly future proof against nearly all changes Microsoft might make.  They would have to completely revamp how security tokens and processes work from the ground up, which is, at this point, something that is extremely unlikely to ever happen.

Since this isn't a bug in this software, I'm going to close this issue.  In-depth discussions are better done on Discord.
