### ISSUE TITLE
When started from a Windows PowerShell window the terminal behaves strangely

### ISSUE THREAD

**Issue by rgl** [cubiclesoft/createprocess-windows#8]
When running `cmd.exe` in a Windows 10 Windows PowerShell window as:

```powershell
.\createprocess.exe /systemtoken c:\Windows\System32\cmd.exe
```

The terminal behaves strangely when I press the ENTER key. It shows some kind of `More?` prompt (which seem to be for some kind of PAGER application):

![image](https://github.com/cubiclesoft/createprocess-windows/assets/43356/959ee347-5f48-4964-b8e4-8421635bbf37)

Have you ever seen this? Known how to fix it?

Please note that this does not happen from a Command Prompt window.

**Comment by cubiclesoft** [comment]
Yeah, weird stuff can happen when you have two console applications running at the same time in the same console.  By default, `createprocess.exe` does not wait for the target process to finish.  Since you are starting a Command Prompt inside a PowerShell window without the `/w` option, createprocess probably isn't waiting for the other prompt to exit, so both applications are reading keyboard input from the console.  There are all kinds of weird bugs with the console subsystem in Windows.  Batch files also present their own unique problems.
